# Copyright (C) 2026 and later: Unicode, Inc. and others.
# License & terms of use: http://www.unicode.org/copyright.html

have_fun: true
code_review:
  disable: false
  comment_severity_threshold: LOW
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: false
    code_review: false
ignore_patterns: []
